# Generated by Django 3.1.4 on 2020-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='main_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_info_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_info_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_info_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_title_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_title_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_title_uz',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
