# Generated by Django 3.1.4 on 2020-12-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201210_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='facebook_icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='google_icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='google_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='instagram_icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='main_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
