# Generated by Django 3.1.4 on 2020-12-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_email_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_email_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='about_email_uz',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email_info_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email_info_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email_info_uz',
        ),
    ]
