# Generated by Django 3.1.4 on 2020-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201211_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_head', models.CharField(blank=True, max_length=256, null=True)),
                ('service_head_en', models.CharField(blank=True, max_length=256, null=True)),
                ('service_head_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('service_head_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('service_logo', models.FileField(blank=True, null=True, upload_to='')),
                ('service_title', models.CharField(blank=True, max_length=256, null=True)),
                ('service_title_en', models.CharField(blank=True, max_length=256, null=True)),
                ('service_title_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('service_title_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('service_info', models.TextField(blank=True, null=True)),
                ('service_info_en', models.TextField(blank=True, null=True)),
                ('service_info_ru', models.TextField(blank=True, null=True)),
                ('service_info_uz', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
            },
        ),
    ]
