# Generated by Django 3.1.4 on 2020-12-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201211_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='consult_logo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='marketing_logo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_logo',
        ),
    ]
