# Generated by Django 3.1.4 on 2020-12-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201211_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_head', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_head_en', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_head_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_head_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_title', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_title_en', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_title_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_title_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('resume_year', models.IntegerField(blank=True, null=True)),
                ('resume_info', models.TextField(blank=True, null=True)),
                ('resume_info_en', models.TextField(blank=True, null=True)),
                ('resume_info_ru', models.TextField(blank=True, null=True)),
                ('resume_info_uz', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume Item',
                'verbose_name_plural': 'Resume Items',
            },
        ),
    ]
