# Generated by Django 3.1.4 on 2020-12-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_form_en', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_form_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_form_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_address_en', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_address_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_address_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('btn_send', models.CharField(blank=True, max_length=256, null=True)),
                ('btn_send_en', models.CharField(blank=True, max_length=256, null=True)),
                ('btn_send_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('btn_send_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Item',
                'verbose_name_plural': 'Contact Items',
            },
        ),
    ]
