# Generated by Django 3.1.4 on 2020-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_ru',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='map_uz',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
